### ISSUE TITLE
can't find variable self

### ISSUE THREAD

**Issue by taghreedalshammari** [hareeqi/react-one-starter#1]
I got this error while running the project on a device
Searching for a solution I found that ``yarn add whatwg-fetch@2.0.4`` will solve the problem!

**Comment by hareeqi** [comment]
What kind of environment are you running it on ?

I just did a fresh install with mac os, node 8 and npm 6 and web version worked without any errors 

make sure you are using the latest node and npm and do a fresh install and it should work.

**Comment by hareeqi** [comment]
just did another fresh install and tested on device ( iPhone ) and it is working fine

Using mac, node 8 and npm 6

Let me know how it goes, thanks

**Comment by taghreedalshammari** [comment]
I'm using Mac with npm 6.4.1 & node v8.12.0. the issue only happens with the mobile including the simulator.

**Comment by hareeqi** [comment]
can you show me a screenshot of the error you get after a fresh install.

Thanks

**Comment by taghreedalshammari** [comment]
<img width="451" alt="screen shot 2018-10-05 at 1 54 35 pm" src="https://user-images.githubusercontent.com/23278493/46531546-430f4280-c8a6-11e8-9c38-a441ef5d3400.png">

**Comment by hareeqi** [comment]
it seems, this is the problem you are talking about, but the last line says it's fixed in expo 30.0.1 which is the one used in this starter.

https://forums.expo.io/t/cant-find-variable-self/13547

Although i am not having this problem, i think modifying package-lock.json will fix it. I will do so 

In the mean time can you please go to node_modules/whatwg-fetch/package.json and confirm what is version number in that package.json file. It should be 2 something to work, if it is 3 something then this might be causing the error

Thanks

**Comment by hareeqi** [comment]
Just updated package-lock.json hopefully a fresh install should fix the issue

**Comment by taghreedalshammari** [comment]
you're right it's -v 3 in the starter .. so the solution is downgrading whatwg-fetch. I thought it was a missing dependency. Thank you!
